[project]
name = "hydrodashboards"
version = "0.6.2"
description = "Dashboards for HydroData"
channels = ["conda-forge"]
platforms = ["win-64"]
readme = "README.md"
license = "MIT"
license-file = "LICENSE"

[tasks]
dash = "python dash\\app.py"
dash_ng = "python dash\\app_NG.py"
vullingsgraad_bokeh = "bokeh serve apps\\vullingsgraad"
vullingsgraad_dash = "python apps\\vullingsgraad_dash\\app\\app.py"

[dependencies]
aiohttp = "*"
nest-asyncio = "*"
pandas = "*"
geopandas = "*"
requests = "*"
bokeh = "*"
fastapi = "*"
dash = "*"
ipykernel = "*"
fiona = "*"
shapely = "*"
pyproj = "*"
ribasim = "==2025.4.0"
pyarrow = ">=10.0.1"
pip = "*"

[pypi-dependencies]
dash-resizable-panels ="*"
dash-extensions = "*"
dash-leaflet = "*"
dash-split-pane = "*"
bokeh-helpers = { path = "bokeh-helpers", editable = true }

