locations_title = dict(dutch="Locaties")
parameters_title = dict(dutch="Parameters")
search_period_start_title = dict(dutch="Start datum")
search_period_end_title = dict(dutch="Eind datum")
update_graph_title = dict(dutch="Grafiek bijwerken")
