name: bokeh3

channels:
  - conda-forge

dependencies:
  - python
  - aiohttp
  - nest-asyncio
  - black
  - jupyter
  - pandas
  - bokeh==3.6.1
  - mkdocs
  - mkdocstrings
  - mkdocstrings-python
  - mkdocs-material
  - geopandas
  - requests
  - schedule
  - pytest
  - pytest-cov
  - pytest-black
  - pytest-flakes
  - twine