name: bokeh

channels:
  - conda-forge
  - defaults

dependencies:
  - aiohttp
  - black
  - jupyter
  - pandas
  - bokeh
  - mkdocs
  - mkdocstrings
  - mkdocstrings-python
  - mkdocs-material
  - geopandas
  - pydantic
  - requests
  - pytest
  - pytest-cov
  - pytest-black
  - pytest-flakes