name: bokeh

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10.5
  - aiohttp
  - nest-asyncio
  - black
  - jupyter
  - pandas=1.5.3
  - bokeh=2.4.3
  - mkdocs
  - mkdocstrings
  - mkdocstrings-python
  - mkdocs-material
  - geopandas=0.12.2
  - requests
  - pytest
  - pytest-cov
  - pytest-black
  - pytest-flakes
  - twine